[package]
name = "argon2_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
base64 = "0.22"
rand = "0.8"

# For Android JNI
[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21.1"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
cbindgen = "0.29.2"
